#%RAML 1.0 DataType
type: object
displayName: ForgotPassword
properties:
  username:
    type: string
    required: true
    displayName:  "username"
    example: "michaelb@example.com"
  factorType:
    type: string 
    required: true
    displayName: "factorType"
    example: "Email"
  relayState:
    type: string
    required: true
    displayName: "relayState"
    example: "/myapp/some/deep/link/i/want/to/return/to"
      
      
      