#%RAML 1.0 Library
usage:
types:
  createuser: !include CreateUserdataType.raml
  changepassword: !include changepassworddataType.raml
  primaryauthentication: !include PrimaryAuthenticationdataType.raml
  forgotpassword: !include ForgotPassworddataType.raml
  createsession: !include CreateSessiondataType.raml
