#%RAML 1.0 DataType
type: object
displayName: "Add Subscription"
properties:
     
  STATUS_TYPE_ID:
    type: number
    displayName: "STATUS_TYPE_ID" 
    example: 1
  SOURCE_LOCATION:
    type: string
    displayName: "SOURCE_LOCATION"  
    example: "ABW"
  DESTINATION_LOCATION:
    type: string
    displayName: "DESTINATION_LOCATION"  
    example: "BSK"
  FROM_TIME:
    type: time-only
    displayName: "FROM_TIME"  
    example: "18:30:00"
  TO_TIME:
    type: time-only  
    displayName: "TO_TIME"
    example: "18:00:00"
  ADVANCE_NOTIFY_TIME_MIN:
    type: number
    displayName: "ADVANCE_NOTIFY_TIME_MIN"  
    example: 30
 
      

          
      
      
      
      
      
       
      