#%RAML 1.0 Library
usage:
types:
  Alerts: !include AlertsdataType.raml
  User: !include UsersdataType.raml
  UpdateUser: !include UsersdataType.raml
  SubscriptionTable: !include SubscriptiondataType.raml
  UpdateSubscription: !include SubscriptiondataType.raml
